version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: ynonp/get-started:part2
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "/Users/ynonperek/tmp/data:/data"
    command: redis-server --appendonly yes
    deploy:
      replicas: 1
    networks:
      - webnet

networks:
  webnet:
